### ISSUE TITLE
Muting the Google voice recognition beep sound

### ISSUE THREAD

**Issue by SelvaKumar92** [StephenVinouze/KontinuousSpeechRecognizer#5]

**Comment by StephenVinouze** [comment]
There is a mute parameter in the manager constructor that is made for this

**Comment by RoyRogerMcFreedy** [comment]
Excusez moi mais il y a un son qui se répète environ toutes les 5 secondes ... j'aimerai qu'il ne se produise uniquement quand je dis le mot clé (ce qu'il fait actuellment) mais quand je ne parle pas il fait quand même un bruit toutes les 5 secondes... Jouer sur AudioManager.ADJUST_MUTE sur STREAM_MUSIC permet de supprimer définitevement les bruits émis par le téléphone... Sauriez vous comment faire ?

**Comment by RoyRogerMcFreedy** [comment]
Le problème c'est que une fois que flag vaut AudioManager.ADJUST_MUTE (pour STREAM_MUSIC ici), et bien on ne peut pas faire de text to Speech directement après car le son sera mute donc on entendra pas le téléphone répondre par exemple (il faut donc augmenter le son du téléphone à chaque fois que la thread recommence...ce qui n'est pas très pratique)... je cherche à remédier à ce problème en réactivant le son une fois le keyword détecté mais je n'y arrive pas ... une petite aide serait la bienvenu s'il vous plaît ;-)

**Comment by kas84** [comment]
shouldn't this line be set to the instance variable shouldMute?

https://github.com/StephenVinouze/KontinuousSpeechRecognizer/blob/06305c404161f200f6a0cf87b44c4c01b903a0ff/core/src/main/kotlin/com/github/stephenvinouze/core/managers/KontinuousRecognitionManager.kt#L50

Thanks for the library! It's great!
